[package]
name = "pb-sharder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
manifest-core = { version = "0.1.0", path = "../manifest-core" }
memmap2 = "0.9"
regex = "1"
safetensors = "0.4"
serde_json = "1"
blake3 = "1.8.3"
