[package]
name = "model-splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
manifest-core = { version = "0.1.0", path = "../manifest-core" }
serde_json = "1"
